name: 'learning'
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs: 
  explore-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: install yarn
          run: npm install --global yarn; export PATH="$HOME/.yarn/bin:$PATH"
        - name: install packages
          run: yarn
        - name: test
          run: yarn test
